# Build and deploy ASP.Net Core Razor app to Azure Web App - bdsagroup9chirprazor
name: Build and deploy Chirp.Razor to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore src/Chirp.Razor/Chirp.Razor.csproj

      - name: Build
        run: dotnet build src/Chirp.Razor/Chirp.Razor.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test src/Chirp.Razor.Tests/Chirp.Razor.Tests.csproj --no-build --verbosity normal

      - name: Publish
        run: dotnet publish src/Chirp.Razor/Chirp.Razor.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: razor-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: razor-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_RAZOR }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_RAZOR }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_RAZOR }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup9chirprazor'
          slot-name: 'Production'
          package: .
