name: Simulate Manual Deploy to Azure

on:
  workflow_dispatch:  # 👈 Only runs manually (can trigger from Actions tab)
  push:
    branches: [ main ]  # optional: auto-run on pushes if you want

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Chirp.Razor/Chirp.Razor.csproj

      - name: Build
        run: dotnet build src/Chirp.Razor/Chirp.Razor.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish src/Chirp.Razor/Chirp.Razor.csproj -c Release -o ./publish

      - name: Create deployment zip
        run: |
          cd publish
          zip -r ../chirp.zip .
          cd ..

      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_RAZOR }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_RAZOR }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_RAZOR }}

  - name: Deploy to Azure Web App
    uses: azure/webapps-deploy@v3
    with:
      app-name: 'bdsagroup9chirprazor'
      package: 'chirp.zip'


      - name: Verify deployment timestamp
        run: |
          echo "Deployment completed. Checking timestamp..."
          az webapp show \
            --name bdsagroup9chirprazor \
            --resource-group bdsagroup9chirprazor \
            --query "lastModifiedTimeUtc"
