name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: bdsagroup9chirpremotedb
  AZURE_WEBAPP_PACKAGE_PATH: 'src/Chirp.Razor'  # ✅ Deploy the Razor app, not CSV service
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Login to Azure using OpenID Connect (no secrets)
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4F55E2DA62464B78A7A64BD26BDE6405 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B04844043F2F48ADA1D59D6A49148578 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B8E9FCB7913B4304819C9CF0AB85D9E1 }}

      # Setup .NET 8
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Restore, build, publish
      - name: Build and publish
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o ./publish

      # ✅ Copy schema and dump files into publish folder
      - name: Copy database seed files
        run: |
          mkdir -p ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish/Data
          cp ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Data/schema.sql ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish/Data/
          cp ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Data/dump.sql ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish/Data/
          echo "Copied schema.sql and dump.sql to deployment package."

      # ✅ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish'

      # Logout from Azure
      - name: Logout
        run: az logout
