name: Build and deploy ASP.Net Core app to Azure Web App - bdsagroup9chirprazor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish app
        run: dotnet publish src/Chirp.Web/Chirp.Web.csproj -c Release -o publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C7AD29EB201E4EE689CF8DD80894FFDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DBE5CE22764E4DD893B9EB32953A856C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2AC3507E872544798DC39F057A3B2697 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup9chirprazor'
          slot-name: 'Production'
          package: '${{ github.workspace }}/publish'
